spring.application.name=api
spring.datasource.url=jdbc:postgresql://eventostec-banco.cruwok2sovqp.sa-east-1.rds.amazonaws.com/postgres
spring.datasource.username=postgres
spring.datasource.password=9uDqIF47[40:*46Om8-~<~uJ9t>d
spring.jpa.hibernate.ddl-auto=none
aws.region=sa-east-1
aws.bucket.name=eventostec-imagenms