ALTER TABLE event ALTER COLUMN image_url TYPE VARCHAR(1000);
ALTER TABLE event ALTER COLUMN description TYPE VARCHAR(1000);
ALTER TABLE event ALTER COLUMN title TYPE VARCHAR(255);
ALTER TABLE event ALTER COLUMN event_url TYPE VARCHAR(1000);